using CarRental.Contracts;
using CustomerA.PdfConsole;

var apiUrl = Environment.GetEnvironmentVariable("RENTAL_API_URL") ?? "http://localhost:5000";
var clientId = Environment.GetEnvironmentVariable("RENTAL_API_CLIENT_ID") ?? "tenant-a";
var clientSecret = Environment.GetEnvironmentVariable("RENTAL_API_CLIENT_SECRET") ?? "secret-a";

Console.WriteLine("Customer A - PDF persistence");
Console.WriteLine("The SaaS tenant is configured for PDF persistence. The customer only integrates through HTTP.");

using var api = new RentalApiClient(apiUrl, clientId, clientSecret);

var pickup = await api.RegisterPickupAsync(
    registrationNumber: "ABC123",
    customerIdentifier: "customer-a-1",
    category: ContractCarCategory.SmallCar,
    pickupTime: DateTimeOffset.UtcNow,
    pickupOdometer: 10_000);

Console.WriteLine($"Pickup created: {pickup.BookingNumber}");
Console.WriteLine("The booking number was generated by the SaaS API; it was not supplied by the customer.");

var returned = await api.RegisterReturnAsync(
    pickup.BookingNumber,
    DateTimeOffset.UtcNow.AddHours(4),
    10_050,
    500m,
    2m);

Console.WriteLine($"Return completed: {returned.BookingNumber}, final price: {returned.FinalPrice:0.00}");
